### ISSUE TITLE
High cpu usage

### ISSUE THREAD

**Issue by zewelor** [ashthespy/Vollibrespot#1]
Hi

I'm using vollibrespot, via volumio spotify connect 2, on rpi zero w. When nothing is playing there is constant cpu usage 80-90%. Is it normal ?

**Comment by ashthespy** [comment]
That shouldn't be the case when idle and not decoding/playing. What version are you running? 
I haven't run it on any `armv6` lately, will give it a go myself as well.

**Comment by zewelor** [comment]
From what I remember it was 0.1.5 ( fresh install via volspotconnect2 ), I can recheck it in a few days. It was weird because 80-90% was no matter if spotify was playing or not.

**Comment by ashthespy** [comment]
I was able reproduce the issue, and have fixed it with e49024043c7bc101e20638dcd88feea357e09bf1, please update to `v0.1.6`.

Thanks for bringing it to my attention, was a silly oversight on my part!

**Comment by zewelor** [comment]
Thanks for fast fix !
