### ISSUE TITLE
ALSA lib pcm.c:8559:(snd_pcm_recover) underrun occurred

### ISSUE THREAD

**Issue by jedie** [ashthespy/Vollibrespot#14]
I have tonaussetzter and see in the logs at this time then always the following message:
```
beocreate vollibrespot[1375]: ALSA lib pcm.c:8559:(snd_pcm_recover) underrun occurred
```

What does it mean? How can i fix it?

**Comment by ashthespy** [comment]
This means that there wasn't enough data (streamed, decoded) for ALSA to play, hence you run into aussetzer..
Do share more details w.t.r what hardware, and what was else was going on when this happens?
