### ISSUE TITLE
Listening activity not being reported

### ISSUE THREAD

**Issue by Starbix** [ashthespy/Vollibrespot#5]
When I listen to music through volspotconnect2, my listening activity doesn't get updated. But as soon as I switch to using the mobile or desktop client, my friends can see what im listening to at the moment.
Is this a known missing feature or a bug?
I already tried totally reinstalling Volumio

**Comment by ashthespy** [comment]
> Is this a known missing feature or a bug?

It is a missing feature - we initially assumed Spotify would keep track of this information server side, but found out that that isn't the case. The underlying API needs to be reverse engineered, then incorporated into [`librespot`](https://github.com/librespot-org/librespot/issues/342)
