### ISSUE TITLE
Add additional scope

### ISSUE THREAD

**Issue by martix90** [ashthespy/Vollibrespot#7]
Hi,
first I wanted to thank you! This library was exactly what I searched for! Librespot Connect + the possibility to control the player and get the track information - perfect.

For my project I want to be able to add certain tracks to the users' favorites.
To do this, the scope "user-library-modify" is needed.
Would it be possible to add this to the hardcoded scopes?
Or even better: have the scopes configurable in the config file? That would be really cool :)

Thank you very much
Martin

**Comment by ashthespy** [comment]
It should be possible, will add it next time I am in there. I need to move to tokio v1.0 which will need some work anyway. Can't give you an ETA though. Sorry!

**Comment by martix90** [comment]
Hi @ashthespy, thank you very much!
I tried to compile it myself with the additional scope but on my RPI Zero that takes unbelievable long and in the end I only got the "Schade" Error-Message when the token should be requested :/

And since I read that "Schade": Greetings from Stuttgart :)

**Comment by ashthespy** [comment]
Moin! :-) 
Sorry for the cryptic errors, I pretty much threw this together for a single use case, and then decided to release it as it might be helpful for others as well..

Anyway, I've added the scope as a quick fix, there should a new release once the CI finishes building.. 
Hope that helps!

EDIT: Done [`v0.2.4`](https://github.com/ashthespy/Vollibrespot/releases/tag/v0.2.4)

**Comment by martix90** [comment]
IIt works like a charm! Thank you very much and I really appreciate your work here!
