### ISSUE TITLE
Device name from config file is ignored

### ISSUE THREAD

**Issue by martix90** [ashthespy/Vollibrespot#8]
Hi again, I've found another issue :)
I'm using a config.toml with this section:

[Authentication]
	shared = true
	device_name = "Webradio"

But the device_name is not used - instead always "Vollibrespot" is used as the device name. The other settings in the file work.

**Comment by ashthespy** [comment]
Glad to know you're finding this useful! 

It should be `device-name` not `device_name`

EDIT: have a look at [this](https://github.com/ashthespy/Volumio-SpotifyConnect/blob/next/volspotify.tmpl) for a sample configuration file :-)

**Comment by martix90** [comment]
Oh I'm very sorry. Thank you very much for the hint. It works now :)
